#!/bin/bash

if [[ $# -ne 0 ]]; then
    echo "No arguments are expected"
    exit 1
fi

cat /etc/passwd | awk -F ':' '{print $6}' | xargs -I{} find {} -maxdepth 1 -type f 2>/dev/null | xargs -I{} stat -c '%Y %U' {} 2>/dev/null | /
sort -k1nr | head -n 1 | awk '{print $2}'


# Напишете скрипт, който извежда името на потребителския акаунт, в чиято home директория има най-скоро променен обикновен файл и кой е този файл. 
# Напишете скрипта с подходящите проверки, така че да бъде валиден инструмент.